version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env.development

  orders:
    build:
      dockerfile: Dockerfile
      context: ./orders
    container_name: orders
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/orders/node_modules
    env_file:
      - ./orders/.env.development

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/users/node_modules
    env_file:
      - ./users/.env.development

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - orders
      - users
    restart: always
    ports:
      - 80:80
